### ISSUE TITLE
hex-rgb upgrade broke the color suggestion feature

### ISSUE THREAD

**Issue by psigns** [Gustu/string-to-color#12]
**Issue**: When doing any color suggestion, string-to-color will always return black.
**Version**: 2.2.1
**Example**: https://repl.it/@PhillipSaenz/DogeYellow

**Expected Result**: `stc("yellow doge")` should return `#f9c325`
**Actual Result**: it returns `#000000`

This issue is also breaking the tests on the master branch.
1. Pull down master
2. Run `npm test`
3. The following tests fail:

```
1) generate
       should return more reddish color:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (test/generate.js:21:16)

  2) generate
       should mix multiple color names with text:

      AssertionError: expected '#000000' to equal '#5b5a65'
      + expected - actual

      -#000000
      +#5b5a65
      
      at Context.<anonymous> (test/generate.js:27:23)

  3) generate
       should return color for yellow doge:

      AssertionError: expected '#000000' to equal '#f9c325'
      + expected - actual

      -#000000
      +#f9c325
      
      at Context.<anonymous> (test/generate.js:38:23)
```

I'm pretty sure this was caused by the recent update from hex-rgb version 1.x to version 4.1.  hex-rgb used to return a 3 element array of numbers representing rgb, but now it returns an object. You can still get it to return an array by the 1.x behavior by adding a second argument `{ format: 'array' }`.

**Before hex-rgb update:**
<img width="710" alt="Screen Shot 2020-07-30 at 6 58 53 PM" src="https://user-images.githubusercontent.com/1140141/89008046-ce996500-d2be-11ea-92e5-8ff934ea99a8.png">

**After hex-rgb update:**
<img width="722" alt="Screen Shot 2020-07-30 at 7 02 26 PM" src="https://user-images.githubusercontent.com/1140141/89008052-d0fbbf00-d2be-11ea-9210-eab0aadcbbb9.png">

If you are open to PR's, I have a fix ready with tests passing.

**Comment by psigns** [comment]
Oh oops.  This is a duplicate of #11.  I'll close the issue but leave the PR open.
